# Generated by Django 3.0.8 on 2020-07-30 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trick_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_learn',
            name='learned',
        ),
        migrations.CreateModel(
            name='learned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.BooleanField(default=False)),
                ('trick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trick_list.To_learn')),
            ],
        ),
    ]
