# Generated by Django 3.0.8 on 2020-07-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trick_list', '0002_auto_20200730_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_learn',
            name='learned',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='learned',
        ),
    ]
